version: '3.4'

networks:
 backend:

services:
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ../src/main/ApiGateway/Dockerfile
    ports: 
       - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
        - backend
  timesheetservice:
    container_name: timesheet-service
    image: ${DOCKER_REGISTRY-}timesheetservice
    build:
      context: .
      dockerfile: ../src/main/Services/TimesheetService/Dockerfile
    networks:
     - backend
  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:18.0.0
    command: 
    - start-dev
    - --features=declarative-user-profile 
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: al@123
      
    ports:
        - "8080:8080"
      
    networks:
     - backend
     
volumes:
  database-data: # named volumes can be managed easier using docker-compose
   

