version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  timesheetservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  tenantservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

