version: '3.4'

networks:
 backend:

services:
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ../src/main/ApiGateway/Dockerfile
    ports: 
       - 5001:443
       - 8001:80
    networks:
        - backend
  timesheetservice:
    container_name: timesheet-service
    image: ${DOCKER_REGISTRY-}timesheetservice
    build:
      context: .
      dockerfile: ../src/main/Services/TimesheetService/Dockerfile
    networks:
     - backend
volumes:
  database-data: # named volumes can be managed easier using docker-compose
   

